"""OASis humanness evaluator (via BioPhi).

Wraps the ``biophi`` library to compute OASis humanness scores.  When
BioPhi is not installed a lightweight mock implementation is used so the
rest of the pipeline can still run.
"""

from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass, field
from typing import Any, Sequence

from antibody_liability_tool.caching import cached
from antibody_liability_tool.evaluators.base import (
    BaseEvaluator,
    ComparisonResult,
    EvaluationResult,
)

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────
# Optional import
# ──────────────────────────────────────────────────────────────────────

_BIOPHI_AVAILABLE = False
try:
    from biophi.humanization.methods.humanness import (  # type: ignore[import-untyped]
        OASisParams,
        oasis_identity,
    )

    _BIOPHI_AVAILABLE = True
    logger.debug("BioPhi / OASis available.")
except ImportError:
    OASisParams = None  # type: ignore[assignment,misc]
    oasis_identity = None  # type: ignore[assignment]
    logger.debug("BioPhi not installed – mock OASis mode will be used.")


# ──────────────────────────────────────────────────────────────────────
# Data classes
# ──────────────────────────────────────────────────────────────────────


@dataclass
class OASisResult:
    """Container for an OASis humanness evaluation.

    Attributes
    ----------
    humanness_score : float
        Overall OASis identity score in ``[0, 1]``.
    percentile : float
        Percentile rank among known human sequences (0–100).
    details : dict[str, Any]
        Extra data returned by BioPhi (per-position identity, etc.).
    is_mock : bool
        ``True`` when the result was generated by the mock fallback.
    """

    humanness_score: float = 0.0
    percentile: float = 0.0
    details: dict[str, Any] = field(default_factory=dict)
    is_mock: bool = False

    def to_metrics(self) -> dict[str, float]:
        return {
            "oasis_humanness": self.humanness_score,
            "oasis_percentile": self.percentile,
        }


# ──────────────────────────────────────────────────────────────────────
# Mock scoring
# ──────────────────────────────────────────────────────────────────────


def _mock_oasis(sequence: str) -> OASisResult:
    """Deterministic mock humanness score derived from the sequence hash.

    Produces a reproducible value in ``[0.4, 1.0)`` so that mock results
    behave plausibly in downstream filters.
    """
    digest = hashlib.sha256(sequence.encode()).hexdigest()
    pseudo = int(digest[:8], 16) / 0xFFFFFFFF
    score = round(0.4 + pseudo * 0.6, 4)
    percentile = round(score * 100, 2)
    return OASisResult(
        humanness_score=score,
        percentile=percentile,
        is_mock=True,
    )


# ──────────────────────────────────────────────────────────────────────
# Real scoring wrapper
# ──────────────────────────────────────────────────────────────────────


@cached(ttl=604800)
def _score_oasis(sequence: str, scheme: str) -> OASisResult:
    """Compute the OASis humanness score (cached on disk)."""
    if not _BIOPHI_AVAILABLE or oasis_identity is None:
        return _mock_oasis(sequence)

    params = OASisParams(scheme=scheme)
    result = oasis_identity(sequence, params=params)

    # biophi returns different shapes depending on the version.
    if isinstance(result, dict):
        score = float(result.get("identity", result.get("score", 0.0)))
        percentile = float(result.get("percentile", score * 100))
        details = result
    elif isinstance(result, (int, float)):
        score = float(result)
        percentile = round(score * 100, 2)
        details = {}
    else:
        # Assume iterable (score, details) tuple
        try:
            score = float(result[0])  # type: ignore[index]
            details = result[1] if len(result) > 1 else {}  # type: ignore[arg-type]
        except (TypeError, IndexError):
            score = 0.0
            details = {}
        percentile = round(score * 100, 2)

    return OASisResult(
        humanness_score=score,
        percentile=percentile,
        details=details,
        is_mock=False,
    )


# ──────────────────────────────────────────────────────────────────────
# Evaluator
# ──────────────────────────────────────────────────────────────────────


class OASisEvaluator(BaseEvaluator):
    """Evaluate antibody sequences for humanness using OASis (BioPhi).

    Parameters
    ----------
    config : dict[str, Any] | None
        ``oasis`` section from the project config.
    """

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        super().__init__(config=config, name="OASis")
        self.min_score_delta: float = float(self.config.get("min_score_delta", 0.0))
        self.scheme: str = self.config.get("scheme", "imgt")

    @property
    def is_available(self) -> bool:
        """Return whether the real BioPhi / OASis package is importable."""
        return _BIOPHI_AVAILABLE

    # ------------------------------------------------------------------
    # Core scoring
    # ------------------------------------------------------------------

    def run(self, sequence: str) -> OASisResult:
        """Compute OASis humanness score for a single sequence."""
        return _score_oasis(sequence, self.scheme)

    # ------------------------------------------------------------------
    # BaseEvaluator interface
    # ------------------------------------------------------------------

    def evaluate(self, sequence: str) -> EvaluationResult:
        try:
            oasis = self.run(sequence)
            return EvaluationResult(
                sequence=sequence,
                evaluator_name=self.name,
                metrics=oasis.to_metrics(),
                raw={"oasis_result": oasis},
                success=True,
            )
        except Exception as exc:  # noqa: BLE001
            self._logger.error("OASis evaluation failed: %s", exc)
            return EvaluationResult(
                sequence=sequence,
                evaluator_name=self.name,
                success=False,
                error_message=str(exc),
            )

    # ------------------------------------------------------------------
    # Comparison helpers
    # ------------------------------------------------------------------

    def compare_to_parent(
        self,
        parent_result: EvaluationResult,
        mutant_result: EvaluationResult,
    ) -> ComparisonResult:
        """Compare mutant vs parent humanness.

        A mutant passes when its OASis score is ≥ the parent score minus
        ``min_score_delta`` (default 0 → must maintain or improve).
        """
        comp = self.compare(
            parent_result,
            mutant_result,
            higher_is_better={"oasis_humanness", "oasis_percentile"},
        )
        # Apply configurable tolerance
        delta = comp.deltas.get("oasis_humanness", 0.0)
        comp.passes_filter = delta >= -abs(self.min_score_delta)
        return comp

    def filter_mutants(
        self,
        parent_sequence: str,
        mutant_sequences: Sequence[str],
    ) -> list[str]:
        """Keep only mutants with OASis humanness ≥ parent score.

        Parameters
        ----------
        parent_sequence : str
            Wild-type sequence.
        mutant_sequences : Sequence[str]
            Candidate mutant sequences.

        Returns
        -------
        list[str]
            Sequences that pass the humanness filter.
        """
        parent_result = self.evaluate(parent_sequence)
        if not parent_result.success:
            self._logger.warning("Parent evaluation failed; returning all mutants unfiltered.")
            return list(mutant_sequences)

        accepted: list[str] = []
        for seq in mutant_sequences:
            mutant_result = self.evaluate(seq)
            if not mutant_result.success:
                self._logger.warning("Skipping failed mutant %.20s…", seq)
                continue
            comp = self.compare_to_parent(parent_result, mutant_result)
            if comp.passes_filter:
                accepted.append(seq)
            else:
                self._logger.debug(
                    "Filtered out mutant (OASis delta: %.4f)",
                    comp.deltas.get("oasis_humanness", 0.0),
                )
        self._logger.info(
            "OASis filter: %d / %d mutants accepted",
            len(accepted),
            len(mutant_sequences),
        )
        return accepted
